'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property frm_X() As Integer
            Get
                Return CType(Me("frm_X"),Integer)
            End Get
            Set
                Me("frm_X") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property frm_Y() As Integer
            Get
                Return CType(Me("frm_Y"),Integer)
            End Get
            Set
                Me("frm_Y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("790")>  _
        Public Property frm_Larg() As Integer
            Get
                Return CType(Me("frm_Larg"),Integer)
            End Get
            Set
                Me("frm_Larg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("590")>  _
        Public Property frm_Haut() As Integer
            Get
                Return CType(Me("frm_Haut"),Integer)
            End Get
            Set
                Me("frm_Haut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property frm_EtatFenetre() As Integer
            Get
                Return CType(Me("frm_EtatFenetre"),Integer)
            End Get
            Set
                Me("frm_EtatFenetre") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bAfficherInfoResultat() As Boolean
            Get
                Return CType(Me("bAfficherInfoResultat"),Boolean)
            End Get
            Set
                Me("bAfficherInfoResultat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bIndexAvecMotsDico() As Boolean
            Get
                Return CType(Me("bIndexAvecMotsDico"),Boolean)
            End Get
            Set
                Me("bIndexAvecMotsDico") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bIndexAvecMotsCourant() As Boolean
            Get
                Return CType(Me("bIndexAvecMotsCourant"),Boolean)
            End Get
            Set
                Me("bIndexAvecMotsCourant") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Fr")>  _
        Public Property sCodeLangueIndex() As String
            Get
                Return CType(Me("sCodeLangueIndex"),String)
            End Get
            Set
                Me("sCodeLangueIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property NbMotsCles() As Integer
            Get
                Return CType(Me("NbMotsCles"),Integer)
            End Get
            Set
                Me("NbMotsCles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bIndexListeMots() As Boolean
            Get
                Return CType(Me("bIndexListeMots"),Boolean)
            End Get
            Set
                Me("bIndexListeMots") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property iIndexType() As Integer
            Get
                Return CType(Me("iIndexType"),Integer)
            End Get
            Set
                Me("iIndexType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Fr;Uk;Us;Es")>  _
        Public Property sListeCodesLanguesIndex() As String
            Get
                Return CType(Me("sListeCodesLanguesIndex"),String)
            End Get
            Set
                Me("sListeCodesLanguesIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bIndexAvecNumeriques() As Boolean
            Get
                Return CType(Me("bIndexAvecNumeriques"),Boolean)
            End Get
            Set
                Me("bIndexAvecNumeriques") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bTexteUnicode() As Boolean
            Get
                Return CType(Me("bTexteUnicode"),Boolean)
            End Get
            Set
                Me("bTexteUnicode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bIndexerAccents() As Boolean
            Get
                Return CType(Me("bIndexerAccents"),Boolean)
            End Get
            Set
                Me("bIndexerAccents") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bAfficherNumOccur() As Boolean
            Get
                Return CType(Me("bAfficherNumOccur"),Boolean)
            End Get
            Set
                Me("bAfficherNumOccur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOccurrencesGras() As Boolean
            Get
                Return CType(Me("bOccurrencesGras"),Boolean)
            End Get
            Set
                Me("bOccurrencesGras") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bOccurrencesCouleur() As Boolean
            Get
                Return CType(Me("bOccurrencesCouleur"),Boolean)
            End Get
            Set
                Me("bOccurrencesCouleur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("yellow;lightgreen;lightblue;silver;turquoise")>  _
        Public Property sCouleursHtml() As String
            Get
                Return CType(Me("sCouleursHtml"),String)
            End Get
            Set
                Me("sCouleursHtml") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bIndexerChapitre() As Boolean
            Get
                Return CType(Me("bIndexerChapitre"),Boolean)
            End Get
            Set
                Me("bIndexerChapitre") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bAfficherChapitreIndex() As Boolean
            Get
                Return CType(Me("bAfficherChapitreIndex"),Boolean)
            End Get
            Set
                Me("bAfficherChapitreIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bAfficherInfoDoc() As Boolean
            Get
                Return CType(Me("bAfficherInfoDoc"),Boolean)
            End Get
            Set
                Me("bAfficherInfoDoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bAfficherNumParag() As Boolean
            Get
                Return CType(Me("bAfficherNumParag"),Boolean)
            End Get
            Set
                Me("bAfficherNumParag") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bAfficherNumPhrase() As Boolean
            Get
                Return CType(Me("bAfficherNumPhrase"),Boolean)
            End Get
            Set
                Me("bAfficherNumPhrase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bNumerotationGlobale() As Boolean
            Get
                Return CType(Me("bNumerotationGlobale"),Boolean)
            End Get
            Set
                Me("bNumerotationGlobale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bAfficherTiret() As Boolean
            Get
                Return CType(Me("bAfficherTiret"),Boolean)
            End Get
            Set
                Me("bAfficherTiret") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property bVerifierUnicode() As Boolean
            Get
                Return CType(Me("bVerifierUnicode"),Boolean)
            End Get
            Set
                Me("bVerifierUnicode") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.VBTextFinder.My.MySettings
            Get
                Return Global.VBTextFinder.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
